### ISSUE TITLE
File/directory does not exist: build/intermediates/runtime_library_classes_jar/debug/classes.jar

### ISSUE THREAD

**Issue by marko-twineahlth** [spotify/ruler#100]
### Current behavior

Command ./gradlew analyze<VariantName>Bundle fails on 99% because: File/directory does not exist: build/intermediates/runtime_library_classes_jar/debug/classes.jar

This is happening with local modules.

In app build.gradle, I am using implementation project(':<name of module>')

Why gradle doesn't create runtime_library_classes_jar in this case? Thanks!

### Expected behavior

The command shouldn't fail with an error

### Steps to reproduce

Run command ./gradlew analyze<VariantName>Bundle

### Versions

'com.android.tools.build:gradle:7.2.1'
'com.spotify.ruler:ruler-gradle-plugin:1.4.0'

**Comment by simonschiller** [comment]
Thanks for reporting! Are you running `analyzeReleaseBundle` or `analyzeDebugBundle`? Or does your have no variants? Could you see what happens if you just run the respective `bundle` (i.e. `bundleDebug` or `bundleRelease`) task - does the issue still appear?

**Comment by simonschiller** [comment]
Great to hear it works for you now, closing this then.
