### ISSUE TITLE
Gradle 8.0.2 + AGP 7.4.2 Break Plugin

### ISSUE THREAD

**Issue by chrisjenx** [spotify/ruler#116]
### Current behavior

Execution failed for task ':analyzeReleaseBundle'.
> java.util.zip.ZipException: zip END header not found

### Expected behavior

Sucessfully Runs

### Steps to reproduce

Update project to Gradle 8.0.2,
Update project to AGP 7.4.2

### Versions

1.4.0 and 2.0-alpha-x

### Anything else?

Will create a branch here updating to show you

**Comment by nathan3d** [comment]
I added support for AGP 7.4.2, so that's not the issue.

Updating Gradle looks like it's going to be a bit more work. It looks like Kotlin needs to be updated, which results in some breaking changes in the Kotlin/JS pieces, will update again once I have more details.

**Comment by chrisjenx** [comment]
Yeah I downgraded to Gradle 7.6.1 and that fixed the issue, it's OK we noticed some other odd behavor with other plugins too (including AGP) SO will probably need to wait for AGP 8.0 before Gradle 8 unfortunatly

**Comment by leinardi** [comment]
Can confirm the issue with `analyzeReleaseBundle` and Gradle 8.x + AGP 8.x.

**Comment by xiahl33** [comment]
Hi @chrisjenx, looks like this issue is addressed by above pr. Do you have an eta of merging this pr and release the fix? Thanks!

**Comment by chrisjenx** [comment]
Not my repo, would need to talk to one of the admins

**Comment by simonschiller** [comment]
CC @nathan3d @ViktorPetrovski

**Comment by nathan3d** [comment]
PR is merged and released as 2.0-alpha-3.

Is the issue solved?

**Comment by chrisjenx** [comment]
> PR is merged and released as 2.0-alpha-3.
> 
> Is the issue solved?

Currently testing

**Comment by chrisjenx** [comment]
Ruler working for us on Gradle 8.1.1, AGP 8.0.2, Kotlin 1.8.21 - Version 2.0.0-alpha4

**Comment by JohnMars** [comment]
Any plans when version `2.0.0` gonna be published?

**Comment by atratarom** [comment]
any one help please

**Comment by nathan3d** [comment]
I've published v2.0.0-beta-1 which should fixes issues with Gradle 8 / AGP 8. Please reopen if the problem still exists.
