### ISSUE TITLE
Accept split apks for CLI

### ISSUE THREAD

**Issue by akniyetc** [spotify/ruler#144]
### Feature description

Could you please add a possibility to provide split apks for your RulerCli tool. In gradle task you build the split apks using bundletool, and extracts all dependencies from those apks. Meanwhile in CLI it accepts only single apk.

### Reasoning

Accepting split apks will provide us the same report as we get running gradle task

**Comment by ViktorPetrovski** [comment]
Hey!

Thanks for your request. Just to make sure, you are interested in extending the RulerCli to accept an `aab` file and create the split apks from it, just as we are doing in the Gradle Task?

**Comment by akniyetc** [comment]
Yes, exactly, thank you

One more thing, is there any specific reason to accept the --dependency-map in a format of jars, assets, resources?
I saw in gradle task, there is also mapping for classes of the project, and no filtering between assets and resources, they goes as a simple DependencyEntry. As far as I understood, it's used for classification in the report. 
I'm asking, because it also affects the final report.

**Comment by nathan3d** [comment]
Hi @akniyetc!  I've added support for this in the latest alpha of CLI. It's not documented yet, but you should be able to pass in the apks already split or alternatively an aab file.

**Comment by akniyetc** [comment]
great news, thank you 🥳
