### ISSUE TITLE
C++ code report is not stripped

### ISSUE THREAD

**Issue by artakhnoyan** [spotify/ruler#67]
### Current behavior

Shows native library more than 80mb

### Expected behavior

Strip C++ code

### Steps to reproduce

Run project `analyze<VariantName>Bundle`, which contains C++ code.

### Versions

1.2.0

**Comment by simonschiller** [comment]
Hi, thanks for this report. It's expected that native libraries show up in the report, as they are included in the app that's shipped to the users. Could you maybe clarify what's not working as expected? And potentially provide a sample project to reproduce?

**Comment by artakhnoyan** [comment]
Hi @simonschiller thanks for the quick reply. I agree that native library should be included. But my report is about how it should be included. When I build my bundle/apk native code got stripped and the size of library become around 8MB. But in your report I've got 80MB for the native library.

**Comment by simonschiller** [comment]
Could you maybe provide is with a demo project that reproduces this issue? We're also using native libraries and their size is reported correctly for us (i.e. the stripped/compressed size, not the raw one).

**Comment by artakhnoyan** [comment]
I cannot provide the project that I working on. What kind of additional information do you need?

**Comment by simonschiller** [comment]
What we'd need is a way to reproduce this issue so we can investigate this further, since it seems to work for us.

We don't need the full project, if it's possible to extract some parts to reproduce what's failing then that would be enough. We'd also be happy if you can open a PR and adapt the sample project in this repo to reproduce this.

**Comment by artakhnoyan** [comment]
So I can provide the configuration of the library. Maybe it will help you to reproduce the issue.
I have native library uploaded to nexus, but it is not stripped. I strip the code during my Android project compilation. In my opinion, the problem is because the library is not stripped initially. However, in my case I cannot strip initially.

**Comment by simonschiller** [comment]
Ruler uses the generated `.aab` file to analyze the size of all components. So assuming the stripped version is included there, it should show the correct size. What would help us is if you could provide the `.aab` of your app (and the generated JSON report).

Keep in mind that there might be sensitive information included there so confirm first if you're comfortable sharing.

**Comment by artakhnoyan** [comment]
Sorry, but I cannot provide the `.aab`. However, I would like to inform you that I analyze `.aab` with Andorid Studio via `Analyze apk` command and the result is different regarding native libraries.

**Comment by artakhnoyan** [comment]
@simonschiller hi,  any updates related to this topic?

**Comment by simonschiller** [comment]
We couldn't reproduce this issue, so unless you can provide a sample project to reproduce this issue we unfortunately won't be able to fix it.

**Comment by artakhnoyan** [comment]
Ok, thanks. I will close the issue and reopen it when I have sample project.
