### ISSUE TITLE
com.android.tools.build:gradle:4.1.3，  There are exceptions. Is it compatible?

### ISSUE THREAD

**Issue by nianzixin** [spotify/ruler#68]

**Comment by simonschiller** [comment]
It should work with 7.1.3, I was able to bump the version and run the tests without any code changes in #69. Can you provide a stack trace?

**Comment by nianzixin** [comment]
> It should work with 7.1.3, I was able to bump the version and run the tests without any code changes in #69. Can you provide a stack trace?
My question is, is 4.1.3 not 7.1.3

**Comment by nianzixin** [comment]
> > It should work with 7.1.3, I was able to bump the version and run the tests without any code changes in #69. Can you provide a stack trace?
> > My question is, is 4.1.3 not 7.1.3

The reason is that my project is very large. If you reference this plug-in, other plug-ins will have to be upgraded. The amount of work is too large

**Comment by simonschiller** [comment]
Oh sorry, I misread that as 7.1.3 when you're talking about 4.1.3. This plugin is not compatible with AGP 4.1.3, the lowest supported version is 7.0.0.
