### ISSUE TITLE
Could refactoring modules automatically change ownership.yaml file?

### ISSUE THREAD

**Issue by radimjanda754** [spotify/ruler#75]
### Feature description

Right now when I refactor modules (like in Android Studio) etc, then this change doesn't apply to ownership.yaml file, meaning user has to rewrite ownership.yaml file manually. 

Could it be possible to make this more automatic, or what do you suggest for module refactoring with spotify/ruler?

### Reasoning

Would be easier to refactor modules

**Comment by simonschiller** [comment]
Thanks for the report! I think that'd make a lot of sense, but I'm not sure how we would implement such a thing. We'd somehow have to make Android Studio aware of the `ownership.yaml` file and its structure. We could write an Android Studio plugin for that, but I think that's probably a little overkill for this purpose.

Unless we find an easier way to do this, I don't think it's worth the effort, even though I agree that it'd be a nice-to-have thing.
